#file: noinspection undefined
server:
  port: 9988
spring:
  datasource:
    username: batch
    password: batch
    url: jdbc:mysql://localhost:3306/batch_db
  jpa:
    hibernate:
      ddl-auto: update
